import { Router, type IRouter, type Request, type Response } from "express";
import PDFDocument from "pdfkit";
import axios from "axios";

const router: IRouter = Router();

const ALOC_TOKEN = process.env.ALOC_TOKEN || "QB-a426946c75c1e80cb2ef";
const ALOC_BASE = "https://questions.aloc.com.ng/api/v2";

interface AlocQuestion {
  id: number;
  question: string;
  option: { a: string; b: string; c: string; d: string; e?: string | null };
  section?: string;
  image?: string;
  answer: string;
  solution?: string;
  examtype: string;
  examyear: string;
}

const JAMB_YEARS = ["2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023"];

function randomYear(): string {
  return JAMB_YEARS[Math.floor(Math.random() * JAMB_YEARS.length)];
}

async function fetchQuestions(subject: string, _year: string, count: number): Promise<AlocQuestion[]> {
  const questions: AlocQuestion[] = [];
  const seenIds = new Set<number>();
  const maxAttempts = Math.min(count * 4, 80);

  for (let i = 0; i < maxAttempts && questions.length < count; i++) {
    try {
      const year = randomYear();
      const url = `${ALOC_BASE}/q?subject=${encodeURIComponent(subject)}&type=utme&year=${year}`;
      const res = await axios.get(url, {
        headers: { AccessToken: ALOC_TOKEN },
        timeout: 8000,
      });
      if (res.data?.status === 200 && res.data?.data) {
        const q = Array.isArray(res.data.data) ? res.data.data[0] : res.data.data;
        if (q && !seenIds.has(q.id)) {
          seenIds.add(q.id);
          questions.push(q);
        }
      }
    } catch {
    }
  }

  return questions.slice(0, count);
}

function cleanText(text: string): string {
  return (text || "")
    .replace(/<[^>]+>/g, " ")
    .replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&").replace(/&nbsp;/g, " ")
    .replace(/&#x2212;/g, "-").replace(/&#x2061;/g, "")
    .replace(/&#x[0-9a-fA-F]+;/g, "")
    .replace(/&[a-z]+;/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function drawPageHeader(doc: PDFKit.PDFDocument, title: string, subtitle: string, examDate: string, duration: string) {
  const W = doc.page.width;

  doc.rect(0, 0, W, 120).fill("#050c1a");

  doc.save();
  for (let x = 0; x < W; x += 6) {
    doc.rect(x, 117, 3, 3).fill(x % 12 === 0 ? "#1d4ed8" : "#0f2a5e");
  }
  doc.restore();

  doc.fontSize(20).fillColor("#3b82f6").font("Helvetica-Bold")
    .text("EXAMCORE", 42, 22);
  doc.fontSize(7.5).fillColor("#64748b").font("Helvetica")
    .text("JAMB CBT PRACTICE PLATFORM", 42, 46);
  doc.fontSize(7).fillColor("#1d4ed8").font("Helvetica")
    .text("www.examcore.ng", 42, 58);

  const centerX = W / 2;
  doc.fontSize(14).fillColor("#f1f5f9").font("Helvetica-Bold")
    .text(title.toUpperCase(), centerX - 180, 18, { width: 360, align: "center" });

  doc.fontSize(9).fillColor("#94a3b8").font("Helvetica")
    .text(subtitle, centerX - 180, 38, { width: 360, align: "center" });

  if (examDate || duration) {
    doc.rect(W - 155, 18, 113, 46).fill("#0f172a").stroke("#1e3a5f");
    doc.fontSize(8).fillColor("#94a3b8").font("Helvetica-Bold")
      .text("EXAM DETAILS", W - 148, 24, { width: 100, align: "left" });
    if (examDate) {
      doc.fontSize(7.5).fillColor("#cbd5e1").font("Helvetica")
        .text(`Date: ${examDate}`, W - 148, 35, { width: 100 });
    }
    if (duration) {
      doc.fontSize(7.5).fillColor("#cbd5e1").font("Helvetica")
        .text(`Duration: ${duration}`, W - 148, 47, { width: 100 });
    }
  }

  doc.rect(0, 120, W, 4).fill("#1d4ed8");
  doc.y = 134;
}

function drawPageFooter(doc: PDFKit.PDFDocument, pageNum: number, totalPages: number, schoolName: string) {
  const W = doc.page.width;
  const H = doc.page.height;

  doc.rect(0, H - 36, W, 36).fill("#050c1a");
  doc.rect(0, H - 36, W, 2).fill("#1e3a5f");

  doc.fontSize(7.5).fillColor("#374151").font("Helvetica")
    .text(schoolName || "ExamCore Admin", 42, H - 22, { width: 160, align: "left" });

  doc.fontSize(7.5).fillColor("#1d4ed8").font("Helvetica-Bold")
    .text("GENERATED BY EXAMCORE X EXAMCORE", 0, H - 22, { width: W, align: "center" });

  doc.fontSize(7.5).fillColor("#374151").font("Helvetica")
    .text(`Page ${pageNum} of ${totalPages}`, W - 120, H - 22, { width: 80, align: "right" });
}

function drawSectionBanner(doc: PDFKit.PDFDocument, subject: string, _year: string, count: number) {
  const W = doc.page.width;
  const margin = 42;
  const y = doc.y + 4;

  doc.rect(margin, y, W - margin * 2, 30).fill("#0f1e3a");
  doc.rect(margin, y, 5, 30).fill("#3b82f6");

  doc.fontSize(12).fillColor("#f1f5f9").font("Helvetica-Bold")
    .text(`${subject.toUpperCase()}`, margin + 16, y + 8, { width: 200 });

  doc.fontSize(9).fillColor("#3b82f6").font("Helvetica")
    .text(`UTME  •  ${count} Questions`, W - margin - 180, y + 9, { width: 180, align: "right" });

  doc.y = y + 40;
}

function drawQuestion(doc: PDFKit.PDFDocument, q: AlocQuestion, num: number, showAnswers: boolean) {
  const W = doc.page.width;
  const margin = 42;
  const contentW = W - margin * 2;
  const innerW = contentW - 32;

  const pageH = doc.page.height;
  if (doc.y > pageH - 160) {
    doc.addPage();
  }

  const qText = cleanText(q.question);
  const opts = ["a", "b", "c", "d"] as const;
  const validOpts = opts.filter((l) => q.option[l] && String(q.option[l]).trim());

  const estHeight = 24 + qText.length * 0.06 * 10 + validOpts.length * 22 + 16;
  if (doc.y + estHeight > pageH - 50) {
    doc.addPage();
  }

  const startY = doc.y;

  doc.rect(margin, startY, contentW, 1.5).fill("#1e3a5f");
  doc.y = startY + 6;

  const numBubbleY = doc.y;
  doc.circle(margin + 11, numBubbleY + 6, 10).fill("#1d4ed8");
  doc.fontSize(8.5).fillColor("#ffffff").font("Helvetica-Bold")
    .text(String(num), margin + 6, numBubbleY + 2, { width: 11, align: "center" });

  const qY = numBubbleY;
  doc.fontSize(10).fillColor("#e2e8f0").font("Helvetica")
    .text(qText, margin + 26, qY, { width: innerW });

  doc.y += 6;

  validOpts.forEach((letter) => {
    const val = cleanText(String(q.option[letter]));
    if (!val) return;

    if (doc.y > pageH - 60) doc.addPage();

    const isCorrect = showAnswers && q.answer.toLowerCase() === letter;
    const optY = doc.y;
    const optBg = isCorrect ? "#0a3020" : "#0b1729";
    const optBorder = isCorrect ? "#16a34a" : "#1e3a5f";
    const optLabelColor = isCorrect ? "#4ade80" : "#3b82f6";
    const optTextColor = isCorrect ? "#86efac" : "#cbd5e1";

    doc.rect(margin + 26, optY, innerW, 20).fill(optBg).stroke(optBorder);

    doc.fontSize(8.5).fillColor(optLabelColor).font("Helvetica-Bold")
      .text(`${letter.toUpperCase()}.`, margin + 32, optY + 5, { width: 16 });

    doc.fontSize(8.5).fillColor(optTextColor).font("Helvetica")
      .text(val, margin + 50, optY + 5, { width: innerW - 28 });

    if (isCorrect) {
      doc.fontSize(7).fillColor("#4ade80").font("Helvetica-Bold")
        .text("✓", margin + innerW + 14, optY + 6, { width: 12 });
    }

    doc.y = optY + 24;
  });

  if (showAnswers && q.solution) {
    const sol = cleanText(q.solution);
    if (sol && sol.length > 5) {
      const solY = doc.y + 2;
      doc.rect(margin + 26, solY, innerW, 1).fill("#1e3a5f");
      doc.y = solY + 6;
      doc.fontSize(8).fillColor("#64748b").font("Helvetica-Oblique")
        .text(`Solution: ${sol.slice(0, 300)}`, margin + 26, doc.y, { width: innerW });
      doc.y += 4;
    }
  }

  doc.y += 12;
}

router.post("/generate", async (req: Request, res: Response) => {
  const {
    title,
    subtitle,
    schoolName,
    examDate,
    duration,
    includeAnswers,
    includeAnswerKey,
    subjectDetails,
  } = req.body;

  if (!subjectDetails || !Array.isArray(subjectDetails) || subjectDetails.length === 0) {
    res.status(400).json({ error: "subjectDetails array is required" });
    return;
  }

  try {
    const questionSets: { subject: string; year: string; questions: AlocQuestion[] }[] = [];

    for (const detail of subjectDetails) {
      const qs = await fetchQuestions(detail.subject, detail.year || "", detail.count || 10);
      questionSets.push({ subject: detail.subject, year: detail.year || "Mixed", questions: qs });
    }

    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 145, bottom: 46, left: 42, right: 42 },
      bufferPages: true,
      info: {
        Title: title || "ExamCore Practice Paper",
        Author: "ExamCore Platform",
        Subject: "JAMB Past Questions",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));

    doc.on("end", () => {
      const range = doc.bufferedPageRange();
      const totalPages = range.count;

      for (let i = 0; i < range.count; i++) {
        doc.switchToPage(i);
        drawPageHeader(doc, title || "JAMB CBT Practice Paper", subtitle || "Unified Tertiary Matriculation Examination", examDate || "", duration || "");
        drawPageFooter(doc, i + 1, totalPages, schoolName || "ExamCore Admin");
      }

      doc.flushPages();

      const pdfBuffer = Buffer.concat(chunks);
      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", `attachment; filename="examcore-practice-paper.pdf"`);
      res.setHeader("Content-Length", pdfBuffer.length);
      res.send(pdfBuffer);
    });

    let globalNum = 1;

    for (const { subject, year, questions } of questionSets) {
      drawSectionBanner(doc, subject, year, questions.length);
      for (const q of questions) {
        drawQuestion(doc, q, globalNum++, includeAnswers === true);
      }
    }

    if (includeAnswerKey && !includeAnswers && questionSets.some((s) => s.questions.length > 0)) {
      doc.addPage();
      doc.y = 150;

      const W = doc.page.width;
      const margin = 42;
      const contentW = W - margin * 2;

      doc.rect(margin, doc.y, contentW, 36).fill("#0f1e3a");
      doc.rect(margin, doc.y, 5, 36).fill("#a855f7");
      doc.fontSize(14).fillColor("#f1f5f9").font("Helvetica-Bold")
        .text("ANSWER KEY", margin + 16, doc.y + 10, { width: contentW - 32 });
      doc.y += 50;

      let keyNum = 1;
      for (const { subject, questions } of questionSets) {
        if (questions.length === 0) continue;

        doc.fontSize(10).fillColor("#3b82f6").font("Helvetica-Bold")
          .text(subject.toUpperCase(), margin, doc.y);
        doc.y += 12;

        const cols = 6;
        const colW = contentW / cols;
        let col = 0;
        const rowStartY = doc.y;

        questions.forEach((q) => {
          const x = margin + col * colW;
          const row = Math.floor(col / cols);
          const y = rowStartY + row * 18;

          if (col % cols === 0 && col > 0) {
            doc.y += 18;
          }

          doc.fontSize(9).fillColor("#e2e8f0").font("Helvetica")
            .text(`${keyNum}.`, x, doc.y, { width: 20 });
          doc.fontSize(9).fillColor("#4ade80").font("Helvetica-Bold")
            .text(q.answer.toUpperCase(), x + 20, doc.y, { width: colW - 22 });

          keyNum++;
          col++;
        });

        doc.y += 28;
      }
    }

    doc.end();
  } catch (err: any) {
    console.error("PDF generation error:", err);
    res.status(500).json({ error: "Failed to generate PDF", message: err.message });
  }
});

export default router;
