import { Router, type IRouter, type Request, type Response } from "express";
import PDFDocument from "pdfkit";
import axios from "axios";

const router: IRouter = Router();

const ALOC_TOKEN = process.env.ALOC_TOKEN || "QB-a426946c75c1e80cb2ef";
const ALOC_BASE = "https://questions.aloc.com.ng/api/v2";

interface AlocQuestion {
  id: number;
  question: string;
  option: { a: string; b: string; c: string; d: string; e?: string | null };
  section?: string;
  image?: string;
  answer: string;
  solution?: string;
  examtype: string;
  examyear: string;
}

const JAMB_YEARS = ["2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023"];

function randomYear(): string {
  return JAMB_YEARS[Math.floor(Math.random() * JAMB_YEARS.length)];
}

async function fetchQuestions(subject: string, _year: string, count: number): Promise<AlocQuestion[]> {
  const questions: AlocQuestion[] = [];
  const seenIds = new Set<number>();
  const maxAttempts = Math.min(count * 4, 80);

  for (let i = 0; i < maxAttempts && questions.length < count; i++) {
    try {
      const year = randomYear();
      const url = `${ALOC_BASE}/q?subject=${encodeURIComponent(subject)}&type=utme&year=${year}`;
      const res = await axios.get(url, {
        headers: { AccessToken: ALOC_TOKEN },
        timeout: 8000,
      });
      if (res.data?.status === 200 && res.data?.data) {
        const q = Array.isArray(res.data.data) ? res.data.data[0] : res.data.data;
        if (q && !seenIds.has(q.id)) {
          seenIds.add(q.id);
          questions.push(q);
        }
      }
    } catch {
    }
  }

  return questions.slice(0, count);
}

function cleanText(text: string): string {
  return (text || "")
    .replace(/<[^>]+>/g, " ")
    .replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&").replace(/&nbsp;/g, " ")
    .replace(/&#x2212;/g, "-").replace(/&#x2061;/g, "")
    .replace(/&#x[0-9a-fA-F]+;/g, "")
    .replace(/&[a-z]+;/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function drawPageHeader(doc: PDFKit.PDFDocument, title: string, jambRegNo: string, duration: string, fullName: string) {
  const W = doc.page.width;
  const margin = 42;
  const contentW = W - margin * 2;

  doc.rect(0, 0, W, 130).fill("#ffffff");

  // — Branding (left) —
  doc.fontSize(16).fillColor("#000000").font("Helvetica-Bold")
    .text("EXAMCORE", margin, 14);
  doc.fontSize(7).fillColor("#000000").font("Helvetica")
    .text("JAMB CBT PRACTICE PLATFORM", margin, 34);
  doc.fontSize(7).fillColor("#000000").font("Helvetica")
    .text("www.examcore.ng", margin, 45);

  // — Exam title (centered, bold) —
  doc.fontSize(15).fillColor("#000000").font("Helvetica-Bold")
    .text(title.toUpperCase(), margin + 90, 16, { width: contentW - 90, align: "center" });

  // — Divider between branding/title and info fields —
  doc.rect(margin, 62, contentW, 0.75).fill("#000000");

  // — Info row: FULL NAME | JAMB REG NO | DURATION —
  const infoY = 70;
  const thirdW = contentW / 3;

  // Full Name
  doc.fontSize(8).fillColor("#000000").font("Helvetica-Bold")
    .text("FULL NAME:", margin, infoY);
  doc.fontSize(9).fillColor("#000000").font("Helvetica-Bold")
    .text(fullName || "________________________________", margin, infoY + 12, { width: thirdW - 10 });

  // JAMB REG NO
  const regX = margin + thirdW;
  doc.fontSize(8).fillColor("#000000").font("Helvetica-Bold")
    .text("JAMB REG NO:", regX, infoY);
  doc.fontSize(9).fillColor("#000000").font("Helvetica-Bold")
    .text(jambRegNo || "________________________________", regX, infoY + 12, { width: thirdW - 10 });

  // Duration
  const durX = margin + thirdW * 2;
  doc.fontSize(8).fillColor("#000000").font("Helvetica-Bold")
    .text("DURATION:", durX, infoY);
  doc.fontSize(9).fillColor("#000000").font("Helvetica-Bold")
    .text(duration || "—", durX, infoY + 12, { width: thirdW - 4 });

  // — Bottom border —
  doc.rect(margin, 126, contentW, 1).fill("#000000");
  doc.y = 142;
}

function drawPageFooter(doc: PDFKit.PDFDocument, pageNum: number, totalPages: number, schoolName: string) {
  const W = doc.page.width;
  const H = doc.page.height;
  const margin = 42;

  doc.rect(margin, H - 36, W - margin * 2, 1).fill("#000000");

  doc.fontSize(7.5).fillColor("#000000").font("Helvetica")
    .text(schoolName || "ExamCore Admin", margin, H - 22, { width: 160, align: "left" });

  doc.fontSize(7.5).fillColor("#000000").font("Helvetica-Bold")
    .text("GENERATED BY EXAMCORE X EXAMCORE", 0, H - 22, { width: W, align: "center" });

  doc.fontSize(7.5).fillColor("#000000").font("Helvetica")
    .text(`Page ${pageNum} of ${totalPages}`, W - margin - 80, H - 22, { width: 80, align: "right" });
}

function drawSectionBanner(doc: PDFKit.PDFDocument, subject: string, _year: string, count: number) {
  const W = doc.page.width;
  const margin = 42;
  const y = doc.y + 4;

  doc.rect(margin, y, W - margin * 2, 26).fill("#f0f0f0").stroke("#000000");

  doc.fontSize(12).fillColor("#000000").font("Helvetica-Bold")
    .text(`${subject.toUpperCase()}`, margin + 10, y + 7, { width: 250 });

  doc.fontSize(9).fillColor("#000000").font("Helvetica")
    .text(`UTME  •  ${count} Questions`, W - margin - 180, y + 8, { width: 180, align: "right" });

  doc.y = y + 36;
}

function drawQuestion(doc: PDFKit.PDFDocument, q: AlocQuestion, num: number, showAnswers: boolean) {
  const W = doc.page.width;
  const margin = 42;
  const contentW = W - margin * 2;
  const innerW = contentW - 32;

  const pageH = doc.page.height;
  if (doc.y > pageH - 160) {
    doc.addPage();
  }

  const qText = cleanText(q.question);
  const opts = ["a", "b", "c", "d"] as const;
  const validOpts = opts.filter((l) => q.option[l] && String(q.option[l]).trim());

  const estHeight = 24 + qText.length * 0.06 * 10 + validOpts.length * 22 + 16;
  if (doc.y + estHeight > pageH - 50) {
    doc.addPage();
  }

  const startY = doc.y;

  doc.rect(margin, startY, contentW, 0.5).fill("#000000");
  doc.y = startY + 6;

  const numY = doc.y;
  doc.fontSize(10).fillColor("#000000").font("Helvetica-Bold")
    .text(`${num}.`, margin, numY, { width: 20 });

  doc.fontSize(10).fillColor("#000000").font("Helvetica")
    .text(qText, margin + 22, numY, { width: innerW });

  doc.y += 6;

  validOpts.forEach((letter) => {
    const val = cleanText(String(q.option[letter]));
    if (!val) return;

    if (doc.y > pageH - 60) doc.addPage();

    const isCorrect = showAnswers && q.answer.toLowerCase() === letter;
    const optY = doc.y;

    doc.rect(margin + 22, optY, innerW, 18).fill("#ffffff").stroke("#cccccc");

    doc.fontSize(8.5).fillColor("#000000").font("Helvetica-Bold")
      .text(`${letter.toUpperCase()}.`, margin + 28, optY + 4, { width: 16 });

    doc.fontSize(8.5).fillColor("#000000").font("Helvetica")
      .text(val, margin + 46, optY + 4, { width: innerW - 28 });

    if (isCorrect) {
      doc.fontSize(8.5).fillColor("#000000").font("Helvetica-Bold")
        .text("✓", margin + innerW + 8, optY + 4, { width: 14 });
    }

    doc.y = optY + 22;
  });

  if (showAnswers && q.solution) {
    const sol = cleanText(q.solution);
    if (sol && sol.length > 5) {
      const solY = doc.y + 2;
      doc.y = solY + 4;
      doc.fontSize(8).fillColor("#000000").font("Helvetica-Oblique")
        .text(`Solution: ${sol.slice(0, 300)}`, margin + 22, doc.y, { width: innerW });
      doc.y += 4;
    }
  }

  doc.y += 10;
}

router.post("/generate", async (req: Request, res: Response) => {
  const {
    title,
    subtitle,
    schoolName,
    examDate,
    duration,
    includeAnswers,
    includeAnswerKey,
    subjectDetails,
  } = req.body;

  if (!subjectDetails || !Array.isArray(subjectDetails) || subjectDetails.length === 0) {
    res.status(400).json({ error: "subjectDetails array is required" });
    return;
  }

  try {
    const questionSets: { subject: string; year: string; questions: AlocQuestion[] }[] = [];

    for (const detail of subjectDetails) {
      const qs = await fetchQuestions(detail.subject, detail.year || "", detail.count || 10);
      questionSets.push({ subject: detail.subject, year: detail.year || "Mixed", questions: qs });
    }

    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 158, bottom: 46, left: 42, right: 42 },
      bufferPages: true,
      info: {
        Title: title || "ExamCore Practice Paper",
        Author: "ExamCore Platform",
        Subject: "JAMB Past Questions",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));

    doc.on("end", () => {
      const range = doc.bufferedPageRange();
      const totalPages = range.count;

      for (let i = 0; i < range.count; i++) {
        doc.switchToPage(i);
        drawPageHeader(doc, title || "JAMB CBT Practice Paper", subtitle || "", duration || "", schoolName || "");
        drawPageFooter(doc, i + 1, totalPages, schoolName || "");
      }

      doc.flushPages();

      const pdfBuffer = Buffer.concat(chunks);
      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", `attachment; filename="examcore-practice-paper.pdf"`);
      res.setHeader("Content-Length", pdfBuffer.length);
      res.send(pdfBuffer);
    });

    let globalNum = 1;

    for (const { subject, year, questions } of questionSets) {
      drawSectionBanner(doc, subject, year, questions.length);
      for (const q of questions) {
        drawQuestion(doc, q, globalNum++, includeAnswers === true);
      }
    }

    if (includeAnswerKey && !includeAnswers && questionSets.some((s) => s.questions.length > 0)) {
      doc.addPage();
      doc.y = 158;

      const W = doc.page.width;
      const margin = 42;
      const contentW = W - margin * 2;

      const bannerY = doc.y;
      doc.rect(margin, bannerY, contentW, 30).fill("#f0f0f0").stroke("#000000");
      doc.fontSize(14).fillColor("#000000").font("Helvetica-Bold")
        .text("ANSWER KEY", margin + 10, bannerY + 8, { width: contentW - 20, lineBreak: false });
      doc.y = bannerY + 44;

      const cols = 6;
      const colW = contentW / cols;
      let keyNum = 1;

      for (const { subject, questions } of questionSets) {
        if (questions.length === 0) continue;

        const subjectY = doc.y;
        doc.fontSize(10).fillColor("#000000").font("Helvetica-Bold")
          .text(subject.toUpperCase(), margin, subjectY, { lineBreak: false });
        doc.y = subjectY + 18;

        let col = 0;
        let rowY = doc.y;

        questions.forEach((q) => {
          if (col === cols) {
            col = 0;
            rowY += 20;
          }

          const x = margin + col * colW;

          doc.fontSize(9).fillColor("#000000").font("Helvetica")
            .text(`${keyNum}.`, x, rowY, { width: 22, lineBreak: false });
          doc.fontSize(9).fillColor("#000000").font("Helvetica-Bold")
            .text(q.answer.toUpperCase(), x + 22, rowY, { width: colW - 24, lineBreak: false });

          keyNum++;
          col++;
        });

        doc.y = rowY + 32;
      }
    }

    doc.end();
  } catch (err: any) {
    console.error("PDF generation error:", err);
    res.status(500).json({ error: "Failed to generate PDF", message: err.message });
  }
});

export default router;
